name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: apt
      run: sudo apt-get install mesa-common-dev libglx-dev libxcursor-dev
      
    - name: compile single-headers.o
      run: gcc -c source/single-headers.c -lm -I./include -I./include/deps
      
    - name: gcc 
      run: gcc source/main.c single-headers.o -lm -lX11 -lGLX -lGL -I./include -I./include/deps
